core/urls.py
from django.urls import path
from .views import *
from .models import *

urlpatterns = [
    path('', index, name='home'),
    path('tax', TaxView.as_view(), name='tax'),
    path('analytics', PromotionListView.as_view(), name='analytics'),
    path('companies/<str:symbol>/', CompanyDetailView.as_view(), name='company-detail'),
]

forum/urls.py
from django.urls import path

from forum.views import *
from forum.models import *

urlpatterns = [
    path('form', FeedView.as_view(), name='main'),
    path('hot', HotQuestionsView.as_view(), name='hot'),
    path('ask', AskView.as_view(), name='ask'),
    path('question/<pk>', QuestionView.as_view(), name='question'),

    path('tag/<str:tag_name>', TagQuestionView.as_view(), name='tag'),
    path('question/<pk>/like', VotesView.as_view(model=Question, vote=LikeDislike.LIKE)),
    path('question/<pk>/dislike', VotesView.as_view(model=Question, vote=LikeDislike.DISLIKE)),
    path('answer/<pk>/like', VotesView.as_view(model=Answer, vote=LikeDislike.LIKE)),
    path('answer/<pk>/dislike', VotesView.as_view(model=Answer, vote=LikeDislike.DISLIKE)),
    path('question/<pk>/isliked', IsLikedView.as_view(model=Question)),
    path('answer/<pk>/isliked', IsLikedView.as_view(model=Answer)),
]

investment/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', include('core.urls')),
    path('', include('users.urls')),
    path('', include('forum.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.utils import timezone

from forum.managers import LikeDislikeManager, TagManager, QuestionManager, AnswerManager
from users.models import User


class Tag(models.Model):
    title = models.CharField(unique=True, verbose_name="Tag", max_length=25)
    objects = TagManager()

    def __str__(self):
        return self.title


class LikeDislike(models.Model):
    LIKE = 1
    DISLIKE = -1

    VOTES = (
        (DISLIKE, 'Не нравится'),
        (LIKE, 'Нравится')
    )

    vote = models.SmallIntegerField(verbose_name="Голос", choices=VOTES)
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    objects = LikeDislikeManager()

    def __str__(self):
        return self.user.username + " liked"


@receiver(pre_delete, sender=LikeDislike)
def add_score(instance, **kwargs):
    instance.content_object.rate -= instance.vote
    instance.content_object.save()


class Question(models.Model):
    author = models.ForeignKey(User, null=False, verbose_name="Question Author", on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now, verbose_name='Question date')
    title = models.CharField(max_length=70, verbose_name='Question Title')
    text = models.TextField(verbose_name='Question full text')
    tags = models.ManyToManyField(Tag, related_name='questions', blank=True, verbose_name='Tags')
    votes = GenericRelation(LikeDislike, related_query_name='question')
    rate = models.IntegerField(default=0, verbose_name='Rate')

    objects = QuestionManager()

    def __str__(self):
        return self.author.username


class Answer(models.Model):
    author = models.ForeignKey(User, null=False, verbose_name="Answer Author", on_delete=models.CASCADE)
    title = models.CharField(max_length=70, verbose_name='Answer Title')
    text = models.TextField(verbose_name='Answer full text')
    question = models.ForeignKey(Question, null=False, verbose_name="Question", on_delete=models.CASCADE)
    votes = GenericRelation(LikeDislike, related_query_name='answer')
    rate = models.IntegerField(default=0, verbose_name='Rate')

    objects = AnswerManager()

    def __str__(self):
        return self.author.username

forum/forms.py
from django import forms
from django.core.validators import RegexValidator

from forum.models import Question, Answer

tagsValidator = RegexValidator(r"[а-яА-Яa-zA-Z]", "Tags should contain letters")


class NewQuestionForm(forms.ModelForm):
    tags = forms.CharField(validators=[tagsValidator])

    class Meta:
        model = Question
        fields = ('title', 'text', 'tags')


class AnswerForm(forms.Form):
    text = forms.CharField()

    class Meta:
        model = Answer
        fields = ('title', 'text')

forum/views.py
from annoying.functions import get_object_or_None
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, FormView

from forum.forms import AnswerForm, NewQuestionForm
from forum.models import Question, Answer, Tag, LikeDislike


class FeedView(ListView):
    paginate_by = 6
    model = Question
    ordering = ["-date"]
    template_name = "forum/feed.html"


class QuestionView(DetailView):
    model = Question
    template_name = "forum/question.html"
    form_class = AnswerForm

    def get_context_data(self, **kwargs):
        return super(QuestionView, self).get_context_data(form=self.form_class, **kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        self.object = self.get_object()
        context = self.get_context_data()
        form = self.form_class(request.POST)
        if form.is_valid():
            Answer.objects.create(author=request.user,
                                  text=form.cleaned_data['text'],
                                  question=self.object)
            return self.render_to_response(context)
        else:
            context['form'] = form
            return self.render_to_response(context)


class HotQuestionsView(ListView):
    paginate_by = 6
    model = Question
    ordering = ["-rate"]
    template_name = "forum/feed.html"


class TagQuestionView(ListView):
    paginate_by = 6
    template_name = "forum/tag_questions.html"
    context_object_name = "questions"

    def get_context_data(self, **kwargs):
        kwargs["tag"] = self.kwargs["tag_name"]
        return super(TagQuestionView, self).get_context_data(**kwargs)

    def get_queryset(self):
        return Tag.objects.questions_by_tag(self.kwargs['tag_name'])


class AskView(LoginRequiredMixin, FormView):
    form_class = NewQuestionForm
    template_name = 'forum/ask.html'
    login_url = 'login'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            question = Question.objects.create(author=request.user,
                                               title=form.cleaned_data['title'],
                                               text=form.cleaned_data['text'])
            form.cleaned_data['tags'].strip()
            for tagTitle in form.cleaned_data['tags'].split():
                tag = Tag.objects.get_or_create(title=tagTitle)[0]
                question.tags.add(tag)
                question.save()
            return HttpResponseRedirect(reverse('question', args=[question.pk]))
        else:
            return self.form_invalid(form)


class VotesView(LoginRequiredMixin, View):
    login_url = 'login'
    model = None
    vote = None

    def post(self, request, pk):
        color = None
        if self.vote == LikeDislike.LIKE:
            color = 'green'
        else:
            color = 'red'
        obj = self.model.objects.get(pk=pk)
        vote_obj = get_object_or_None(LikeDislike, content_type=ContentType.objects.get_for_model(obj),
                                      object_id=pk,
                                      user=request.user)
        if not vote_obj:
            new = LikeDislike(vote=self.vote, user=request.user,
                              content_object=obj)
            new.save()
            new.content_object.rate += self.vote
            new.content_object.save()

            return JsonResponse({'rate': new.content_object.rate, 'color': color})
        if vote_obj.vote == self.vote:
            return JsonResponse({'rate': vote_obj.content_object.rate, 'color': color})
        else:
            vote_obj.delete()
            return JsonResponse({'rate': vote_obj.content_object.rate, 'color': 'black'})


class IsLikedView(LoginRequiredMixin, View):
    login_url = 'login'
    model = None

    def post(self, request, pk):
        obj = self.model.objects.get(pk=pk)
        vote_obj = get_object_or_None(LikeDislike, content_type=ContentType.objects.get_for_model(obj),
                                      object_id=pk,
                                      user=request.user)
        if not vote_obj:
            return JsonResponse({'isliked': 0})
        if vote_obj.vote == 1:
            return JsonResponse({'isliked': 1})
        else:
            return JsonResponse({'isliked': -1})

templates/forum/ask.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
Задать вопрос
{% endblock %}


{% block styles %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8 col-md-8 offset-md-1 content">
            <div class="mt-5">

                <h1 class="mb-5">Новый вопрос</h1>

                <form  method="post" style="width: 70%;">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Заголовок</label>
                        <div class="col-sm-10">
                            {% render_field form.title type="text" class+="form-control" required='True' %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Описание</label>
                        <div class="col-sm-10">
                            {% render_field form.text type="textarea" rows='10' class+="form-control" required='True' %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Тег</label>
                        <div class="col-sm-10">
                            {% render_field form.tags|add_error_class:"is-invalid" type="text" class+="form-control" required='True' %}
                            <div class="invalid-feedback">
                                {{ form.tags.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary btn-lg mt-3" style="padding-left: 2.5rem; padding-right: 2.5rem;">Задать вопрос</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/forum/feed.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Форум
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/feed.css' %}">
{% endblock %}

{% block content %}
<div class="container px-4 px-lg-5">
  <div class="mt-5">
    <h1>Список вопросов</h1>
    <a class="d-inline-block " href="{% url 'hot' %}" style="text-decoration: none">Сортировка по рейтингу</a>
  </div>
  <div class="container-feed">
    {% for question in question_list %}
    <div class="card-feed">
      <div class="card__body">
        {% for tag in question.tags.all %}
        <a href="{% url 'tag' tag %}" class="tag tag-blue " style="text-decoration: none">{{ tag }}</a>
        {% endfor %}
        <h4><a href="{% url 'question' question.pk %}" style="text-decoration: none">{{ question.title }}</a></h4>
        <p class="items-text" >{{ question.text }}</p>
      </div>
      <div class="card__footer">
        <div class="user">
          <img src={{question.author.avatar.url}} width="64" height="64" class="rounded-circle">
          <div class="user__info">
            <h5>{{question.author.username}}</h5>
            <small>{{question.date}}</small>
          </div>
        </div>
        <div style=" padding-left: 63px;">
          <div class="mb-1" style="width: 55px">
            <span>{{ question.rate }}</span>
            <i data-pk="{{question.id}}" data-type="question" class="fa fa-plus mr-1" aria-hidden="true"></i>
            <i data-pk="{{question.id}}" data-type="question" class="fa fa-minus" aria-hidden="true"></i>
          </div>
          <a style="text-decoration: none" href="{% url 'question' question.pk %}" class="text-dark">
            <span>{{ question.answer_set.count }}</span>
            <i class="bi bi-chat-fill"></i>
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% include "components/_paginator.html" %}
</div>
{% endblock %}

templates/forum/question.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
Ответы на вопрос
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/question_details.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-8 col-md-8 offset-md-1 content">
            <div class="container mr-2 pr-3">
                <div class="row details-post pb-3 border-bottom">
                    <div class="col-8 col-lg-2">
                        <div class="mb-2 mb-lg-3"><img  class="rounded-circle" style="width: 110px; height: 110px;" src={{question.author.avatar.url}}></div>
                        <h6>{{question.author.username}} </h6>
                        <div class="mt-2">
                            <span class="mr-1">{{ question.rate }}</span>
                            <i data-pk="{{question.id}}" data-type="question" class="fa fa-plus mr-1" aria-hidden="true"></i>
                            <i data-pk="{{question.id}}" data-type="question" class="fa fa-minus" aria-hidden="true"></i>
                        </div>
                    </div>
                    <div class="col-12 col-lg-8">
                        <h3>{{ question.title }}</h3>
                        <div class="deatils-post-text">
                            {{ question.text }}
                        </div>
                        <div class="details-post-bottom mt-2">
                            <div class="details-post-bottom-tags">
                                <span>Тег:</span>
                                {% for tag in question.tags.all %}
                                <a class="tag" href="{% url 'tag' tag %}" style="text-decoration: none">{{ tag }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% for answer in question.answer_set.all %}
                <div class="row details-post-comment">
                    <div class="col-8 col-lg-2">
                        <div class="mb-2 mb-lg-3"><img class="rounded-circle" style="width: 75px; height: 75px;" src={{answer.author.avatar.url}}></div>
                          <h6>{{answer.author.username}} </h6>
                        <div class="details-post-rate">
                            <span class="mr-1">{{ answer.rate }}</span>
                            <i data-pk="{{answer.id}}" data-type="answer" class="fa fa-plus mr-1" aria-hidden="true"></i>
                            <i data-pk="{{answer.id}}" data-type="answer" class="fa fa-minus" aria-hidden="true"></i>
                        </div>
                    </div>
                    <div class="col-12 col-lg-8">
                        <div class="details-post-text d-md-block">
                            {{ answer.text }}
                        </div>
                    </div>
                </div>
                {% endfor %}
                <form class="detail-post-comment-form border-top" action="#" method="post">
                    {% csrf_token %}
                  <div class="form-group row">
                        <div class="col-sm-10">
                            {% render_field form.text type="textarea" rows='10' class+="form-control form-control-lg" required='True'%}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-10">
                                <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary btn-lg mt-3" style="padding-left: 2.5rem; padding-right: 2.5rem;">Ответить</button>
                        </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div style="height: 10rem"></div>
{% endblock %}

templates/forum/tag_questions.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Тег: {{ tag }}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/feed.css' %}">
{% endblock %}

{% block content %}
<div class="container px-4 px-lg-5 mt-5">
   <div class="feed-top">
            <span class="mr-2 h1">Тег:</span>
            <span>{{ tag }}</span>
        </div>
    <div class="container-feed">
        {% for question in questions %}
        <div class="card-feed">
            <div class="card__body">
                {% for tag in question.tags.all %}
                <a href="{% url 'tag' tag %}" class="tag tag-blue " style="text-decoration: none">{{ tag }}</a>
                {% endfor %}
                <h4><a href="{% url 'question' question.pk %}" style="text-decoration: none">{{ question.title }}</a></h4>
                <p class="items-text" >{{ question.text }}</p>
            </div>
            <div class="card__footer">
                <div class="user">
                    <img src={{question.author.avatar.url}} width="64" height="64" class="rounded-circle">
                    <div class="user__info">
                        <h5>{{question.author.username}}</h5>
                        <small>{{question.date}}</small>
                    </div>
                </div>
                <div style=" padding-left: 63px;">
                    <div class="mb-1" style="width: 55px">
                        <span>{{ question.rate }}</span>
                        <i data-pk="{{question.id}}" data-type="question" class="fa fa-plus mr-1" aria-hidden="true"></i>
                        <i data-pk="{{question.id}}" data-type="question" class="fa fa-minus" aria-hidden="true"></i>
                    </div>
                    <a style="text-decoration: none" href="{% url 'question' question.pk %}" class="text-dark">
                        <span>{{ question.answer_set.count }}</span>
                        <i class="bi bi-chat-fill"></i>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% include "components/_paginator.html" %}
</div>
{% endblock %}